=== dani-zahonyi/nyelvtech/családfa/csaladfa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="nemType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ferfi"/>
      <xs:enumeration value="no"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="csaladfa" type="csaladfaType"/>
  <xs:complexType name="szemelyType">
    <xs:sequence>
      <xs:element type="nevType" name="nev"/>
      <xs:element type="xs:date" name="szuletesi_ido"/>
      <xs:element type="hazastarsType" name="hazastars" minOccurs="0"/>
      <xs:element type="gyerekType" name="gyerek" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="testverType" name="testver" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
    <xs:attribute type="nemType" name="sex" use="optional"/>
  </xs:complexType>
  <xs:complexType name="testverType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="csaladfaType">
    <xs:sequence>
      <xs:element type="szemelyType" name="szemely" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="nevType">
    <xs:sequence>
      <xs:element type="xs:string" name="vezeteknev" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element type="xs:string" name="keresztnev" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="gyerekType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="hazastarsType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== dani-zahonyi/nyelvtech/családfa/csaladfa.xml
<?xml version="1.0" encoding="UTF-8"?>


        <!--  XSL  -->
<?xml-stylesheet type="text/xsl" href="csaladfa.xsl" ?>

        <!--  CSS  -->
<!--<?xml-stylesheet type="text/css" href="csaladfa.css" ?>-->
<csaladfa  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="csaladfa.xsd" >

    <szemely id="g020" sex="ferfi">
        <nev><vezeteknev>Varga</vezeteknev><keresztnev>Tamás</keresztnev></nev>
        <szuletesi_ido>1931-07-14</szuletesi_ido>
        <testver id="g01"/>
    </szemely>
    <szemely id="g010" sex="ferfi">
    <nev><vezeteknev>Varga</vezeteknev><keresztnev>Mihály</keresztnev></nev>
    <szuletesi_ido>1934-02-22</szuletesi_ido>
        <gyerek id="m011"/>
        <testver id="g020"/>
    </szemely>

    <szemely id="m011" sex="no">
        <nev><vezeteknev>Záhonyiné</vezeteknev><vezeteknev>Varga</vezeteknev><keresztnev>Julianna</keresztnev></nev>
        <szuletesi_ido>1959-07-22</szuletesi_ido>
        <hazastars id="f011"/>
        <gyerek id="c012" />
        <gyerek id="c022" />
        <gyerek id="c032" />
    </szemely>

    <szemely id="f011" sex="ferfi">
        <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>György</keresztnev></nev>
        <szuletesi_ido>1965-07-15</szuletesi_ido>
        <hazastars id="m011"/>
        <gyerek id="c012" />
        <gyerek id="c022" />
        <gyerek id="c032" />
    </szemely>

    <szemely id="c012" sex="no">
        <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Rebeka</keresztnev></nev>
        <szuletesi_ido>1986-09-17</szuletesi_ido>
        <hazastars id="f012"/>
        <testver id="c022"/>
        <testver id="c032"/>
    </szemely>
    <szemely id="f02" sex="ferfi">
        <nev><vezeteknev>Gecse</vezeteknev><keresztnev>Milán</keresztnev></nev>
        <szuletesi_ido>1985-10-06</szuletesi_ido>
        <hazastars id="c012"/>
    </szemely>
    <szemely id="c022" sex="ferfi">
        <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Marci</keresztnev><keresztnev>Ferenc</keresztnev></nev>
        <szuletesi_ido>1989-02-01</szuletesi_ido>
        <testver id="c012"/>
        <testver id="c032"/>
    </szemely>

    <szemely id="c032" sex="ferfi">
        <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Dani</keresztnev></nev>
        <szuletesi_ido>1991-04-30</szuletesi_ido>
        <testver id="c022"/>
        <testver id="c012"/>
    </szemely>


</csaladfa>

=== dani-zahonyi/nyelvtech/családfa/csaladfa_treestructure.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="csaladfa01.css" ?>
<csaladfa  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="csaladfa.xsd" >
   <szemely id="g01" sex="ferfi">
       <nev><vezeteknev>Varga</vezeteknev><keresztnev>Mihály</keresztnev></nev>
       <szuletesi_ido>1934-02-22</szuletesi_ido>
       <gyerek id="m01" sex="no">
           <nev><vezeteknev>Záhonyiné Varga</vezeteknev><keresztnev>Julianna</keresztnev></nev>
            <szuletesi_ido>1959-07-22</szuletesi_ido>
        <hazastars id="d01" sex="ferfi">
            <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>György</keresztnev></nev>
            <szuletesi_ido>1965-07-15</szuletesi_ido>
        </hazastars>

        <gyerek id="c01" sex="no">
            <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Rebeka</keresztnev></nev>
            <szuletesi_ido>1986-09-17</szuletesi_ido>
            <hazastars id="f01" sex="ferfi">
                <nev><vezeteknev>Gecse</vezeteknev><keresztnev>Milán</keresztnev></nev>
                <szuletesi_ido>1985-10-06</szuletesi_ido>
            </hazastars>
            <testver id="c02" sex="ferfi">   <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Marci</keresztnev><keresztnev>Ferenc</keresztnev></nev>
                <szuletesi_ido>1989-02-01</szuletesi_ido></testver>
            <testver id="c03" sex="ferfi">      <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Dani</keresztnev></nev>
                <szuletesi_ido>1991-04-30</szuletesi_ido></testver>
        </gyerek>
        <gyerek id="c02" sex="ferfi">
            <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Marci</keresztnev><keresztnev>Ferenc</keresztnev></nev>
            <szuletesi_ido>1989-02-01</szuletesi_ido>
            <testver id="c01"  sex="no"> <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Rebeka</keresztnev></nev>
                <szuletesi_ido>1986-09-17</szuletesi_ido></testver>
            <testver id="c03" sex="ferfi">      <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Dani</keresztnev></nev>
                <szuletesi_ido>1991-04-30</szuletesi_ido></testver>
       </gyerek>
        <gyerek id="c03" sex="ferfi">
            <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Dani</keresztnev></nev>
            <szuletesi_ido>1991-04-30</szuletesi_ido>
            <testver id="c02" sex="ferfi">   <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Marci</keresztnev><keresztnev>Ferenc</keresztnev></nev>
                <szuletesi_ido>1989-02-01</szuletesi_ido></testver>
            <testver id="c01"  sex="no"> <nev><vezeteknev>Záhonyi</vezeteknev><keresztnev>Rebeka</keresztnev></nev>
                <szuletesi_ido>1986-09-17</szuletesi_ido></testver>
      </gyerek>
    </gyerek>
       <testver id="g02"  sex="ferfi">    <nev><vezeteknev>Varga</vezeteknev><keresztnev>Tamás</keresztnev></nev>
           <szuletesi_ido>1931-07-14</szuletesi_ido></testver>
   </szemely>
    <szemely id="g02" sex="ferfi">
        <nev><vezeteknev>Varga</vezeteknev><keresztnev>Tamás</keresztnev></nev>
        <szuletesi_ido>1931-07-14</szuletesi_ido>
        <testver id="g01"  sex="ferfi"> <nev><vezeteknev>Varga</vezeteknev><keresztnev>Mihály</keresztnev></nev>
            <szuletesi_ido>1934-02-22</szuletesi_ido></testver>
    </szemely>
</csaladfa>
